version: '3.4'

services:
  basketdb:
    image: redis

  catalogdb:
    image: mongo

  discountdb:
    image: postgres

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.Api/Dockerfile

volumes:
  mongo_data:    
  portainer_data:
  postgres_data:
  pgadmin_data:


